services:
  - type: web
    name: ai-outreach-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn combined_server:app --host 0.0.0.0 --port $PORT
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false